id: nixos-test-node-config-inherit-pkgs
language: Nix
# inherit pkgs; -> pkgs = config.node.pkgs;
rule:
  all:
    - kind: inherit
    - regex: "^inherit\\s+pkgs\\s*;$"
    - inside:
        matches: nixos-test-outer-function
        stopBy: end
    - not:
        inside:
          matches: nixos-test-pkgs-shadowing-function
          stopBy: end
    - not:
        inside:
          matches: nixos-test-config-shadowing-function
          stopBy: end
    - inside:
        matches: nixos-test-node-config-binding
        stopBy: end
fix: pkgs = config.node.pkgs;
